# -*- coding: utf-8 -*-
{
    'name': "Quatrix Modifications",
    'summary': """Quatrix inheritance module""",
    'description': """Quatrix module for custom modifications on the core models.""",
    'author': "Murunga Kibaara",
    'website': "http://www.quatrixglobal.com",
    'category': 'Accounts',
    'version': '0.1',
    'depends': ['base', 'sale', 'purchase', 'account', 'product', 'fleet', 'web', 'accounting_pdf_reports', 'quatrix_billing_module'],
    'data': [
        'security/ir.model.access.csv',
        'views/sale_views.xml',
        'views/purchase_views.xml',
        'views/account_views.xml',
        'views/account_payment.xml',
        'views/res_config_settings.xml',
        'views/templates.xml',
        'views/product_views.xml',
        'views/fleet_views.xml',
        'views/res_users_views.xml',
        'views/web_login.xml',
        'reports/sale_report.xml',
        'reports/account_report.xml',
        'reports/purchase_report.xml',
        'wizards/wizard.xml',
        'wizards/accounting_rc_wizard.xml',
        'wizards/report.xml',
        'wizards/template.xml',
        # 'wizards/accounting_rc_template.xml',
        'wizards/sale_report_wizard.xml',
        'wizards/sale_uninvoiced_template.xml'
    ],
}
